const { Client } = require("pg");

const SQL = `
CREATE TABLE IF NOT EXISTS categories (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS subcategories(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR (255) NOT NULL UNIQUE,
    category_id INTEGER FOREIGN KEY NOT NULL REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS products(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    brand VARCHAR (255) NOT NULL,
    model VARCHAR (255) NOT NULL UNIQUE,
    price DECIMAL(10,2) NOT NULL,
    quantity INTEGER NOT NULL,
    subcategory_id INTEGER FOREIGN KEY NOT NULL REFERENCES subcategories(id),
)

CREATE TABLE IF NOT EXISTS attributes(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    
)
`;
